[package]
edition = "2021"
name = "exon-examples"
version = "0.1.0"

[dependencies]
arrow = {workspace = true}
datafusion = {workspace = true}
exon = {path = "../exon"}
tokio = {version = "1", features = ["io-util"]}
