[package]
edition = "2021"
name = "exon-examples"
version.workspace = true

[dependencies]
arrow = { workspace = true }
datafusion = { workspace = true }
exon = { path = "../exon/exon-core", features = ["all"] }
tokio = { version = "1", features = ["io-util"] }
