[package]
edition = "2021"
name = "exon-exome"
version = "0.1.0"

[dependencies]
async-trait = "0.1.72"
datafusion.workspace = true
exon = {path = "../exon", features = ["all"]}
prost = "*"
tokio = "1.29.1"
tonic = "*"
url = "2.4.0"
