[package]
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "exon-test"
readme.workspace = true
repository.workspace = true
version = "0.3.4-beta.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = {workspace = true}
object_store = {workspace = true}
