# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_exonr_wrappers", use_symbols = TRUE, package_name = "exonr")

#' @docType package
#' @usage NULL
#' @useDynLib exonr, .registration = TRUE
NULL

#' Copy the inferred exon table from the given path into the given stream.
#' @export
read_inferred_exon_table <- function(file_path, stream_ptr) .Call(wrap__read_inferred_exon_table, file_path, stream_ptr)

ExonSessionContext <- new.env(parent = emptyenv())

ExonSessionContext$new <- function() .Call(wrap__ExonSessionContext__new)

ExonSessionContext$sql <- function(query) .Call(wrap__ExonSessionContext__sql, self, query)

#' @export
`$.ExonSessionContext` <- function (self, name) { func <- ExonSessionContext[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ExonSessionContext` <- `$.ExonSessionContext`

RDataFrame <- new.env(parent = emptyenv())

RDataFrame$print <- function() .Call(wrap__RDataFrame__print, self)

RDataFrame$to_arrow <- function(stream_ptr) .Call(wrap__RDataFrame__to_arrow, self, stream_ptr)

#' @export
`$.RDataFrame` <- function (self, name) { func <- RDataFrame[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RDataFrame` <- `$.RDataFrame`


# nolint end
