# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_exonr_wrappers", use_symbols = TRUE, package_name = "exonr")

#' @docType package
#' @usage NULL
#' @useDynLib exonr, .registration = TRUE
NULL

#' Copy the inferred exon table from the given path into the given stream.
#' @export
read_inferred_exon_table <- function(file_path, stream_ptr) invisible(.Call(wrap__read_inferred_exon_table, file_path, stream_ptr))


# nolint end
