[package]
name = "exon-zarr"
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow-zarr = { path = "/Users/thauck/personal/code/github.com/tshauck/arrow-zarr" }
arrow = { workspace = true }
object_store = { workspace = true }
futures = { workspace = true }
